import one from "./assets/images/1.jpg";
import two from "./assets/images/2.jpg";
import three from "./assets/images/3.jpg";
import four from "./assets/images/4.jpg";
import five from "./assets/images/5.jpg";
import six from "./assets/images/6.jpg";
import seven from "./assets/images/7.jpg";
import eight from "./assets/images/8.jpg";
import nine from "./assets/images/9.jpg";
import ten from "./assets/images/10.jpg";
import eleven from "./assets/images/11.jpg";
import twelve from "./assets/images/12.jpg";
import thirteen from "./assets/images/13.jpg";
import fourteen from "./assets/images/14.jpg";
import fifteen from "./assets/images/15.jpg";
import sixteen from "./assets/images/16.jpg";
import seventeen from "./assets/images/17.jpg";
import eighteen from "./assets/images/18.jpg";
import nineteen from "./assets/images/19.jpg";
import twenty from "./assets/images/20.jpg";
import twentyone from "./assets/images/21.jpg";
import twentytwo from "./assets/images/22.jpg";
import twentythree from "./assets/images/23.jpg";
import twentyfour from "./assets/images/24.jpg";
import twentyfive from "./assets/images/25.jpg";
import twentysix from "./assets/images/26.jpg";
import twentyseven from "./assets/images/27.jpg";
import twentyeight from "./assets/images/28.jpg";
import twentynine from "./assets/images/29.jpg";
import thirty from "./assets/images/30.jpg";
import thirtyone from "./assets/images/31.jpg";
import thirtytwo from "./assets/images/33.jpg";
import thirtythree from "./assets/images/33.jpg";
import thirtyfour from "./assets/images/34.jpg";
import thirtyfive from "./assets/images/35.jpg";
import thirtysix from "./assets/images/36.jpg";
import thirtyseven from "./assets/images/37.jpg";
import thirtyeight from "./assets/images/38.jpg";
import thirtynine from "./assets/images/39.jpg";
import fourty from "./assets/images/40.jpg";
import fourtyone from "./assets/images/41.jpg";
import fourtytwo from "./assets/images/42.jpg";

var products = [
  {
    name: "Scorpio Galaxy",
    id: 1,
    thumb: one,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Letter E",
    id: 2,
    thumb: two,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 1",
    id: 3,
    thumb: three,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "French Stripes 1",
    id: 4,
    thumb: four,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "French Stripes 2",
    id: 5,
    thumb: five,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "French Stripes 3",
    id: 6,
    thumb: six,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 2",
    id: 7,
    thumb: seven,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Duo Tone 1",
    id: 8,
    thumb: eight,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Duo Tone 2",
    id: 9,
    thumb: nine,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Duo Tone 3",
    id: 10,
    thumb: ten,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 3",
    id: 11,
    thumb: eleven,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Squid Games 4",
    id: 12,
    thumb: twelve,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower Pot",
    id: 13,
    thumb: thirteen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Green Plus",
    id: 14,
    thumb: fourteen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 1",
    id: 15,
    thumb: fifteen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 2",
    id: 16,
    thumb: sixteen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Woman in Cup",
    id: 17,
    thumb: seventeen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 3",
    id: 18,
    thumb: eighteen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 4",
    id: 19,
    thumb: nineteen,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 5",
    id: 20,
    thumb: twenty,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Human Art 6",
    id: 21,
    thumb: twentyone,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Gemini Galaxy",
    id: 22,
    thumb: twentytwo,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 1",
    id: 23,
    thumb: twentythree,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 2",
    id: 24,
    thumb: twentyfour,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 3",
    id: 25,
    thumb: twentyfive,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 4",
    id: 26,
    thumb: twentysix,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Clouds 5",
    id: 27,
    thumb: twentyseven,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Green Leaves",
    id: 28,
    thumb: twentyeight,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Hello Flower",
    id: 29,
    thumb: twentynine,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower",
    id: 30,
    thumb: thirty,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower Art",
    id: 31,
    thumb: thirtyone,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Be(e) Kind",
    id: 32,
    thumb: thirtytwo,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Love and Pizza",
    id: 33,
    thumb: thirtythree,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Butterflies",
    id: 34,
    thumb: thirtyfour,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Be Okay",
    id: 35,
    thumb: thirtyfive,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Beautiful Person",
    id: 36,
    thumb: thirtysix,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Strawberry Day",
    id: 37,
    thumb: thirtyseven,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Get a Dog",
    id: 38,
    thumb: thirtyeight,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "White Flowers",
    id: 39,
    thumb: thirtynine,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Flower 2",
    id: 40,
    thumb: fourty,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Happy",
    id: 41,
    thumb: fourtyone,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
  {
    name: "Letter A",
    id: 42,
    thumb: fourtytwo,
    price: "$12.00",
    favorite: false,
    icon: "cart-plus",
    order: "1",
    phone: "",
  },
];

var smartphones = {
  iPhone: [
    "13 Pro Max",
    "13 Pro",
    "13",
    "13 Mini",
    "12 Pro Max",
    "12 / 12 Pro",
    "12 Mini",
    "11 Pro Max",
    "11 Pro",
    "11",
    "XS Max",
    "XR",
    "X / XS",
    "6 Plus / 7 Plus / 8 Plus",
    "7 / 8 / SE(2020)",
    "6 / 6 S",
  ],
  Samsung: [
    "S21 Ultra",
    "S21 FE",
    "S21 Plus",
    "S21",
    "A52 5G",
    "A42 5G",
    "S20 FE",
    "S20 Ultra",
    "S20 Plus",
    "S20",
    "S10",
    "S10 Plus",
    "S10e",
    "S9",
    "S8",
  ],
  Pixel: ["6 Pro", "6", "5a 5G", "5", "4a 5G", "4a", "4XL", "3a"],
};

var cart = [];

export default products;
export { smartphones, cart };
